language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "10"
services: mongodb
before_install:
  - if [[ `npm -v` != 3* ]]; then npm i -g npm@3; fi
after_success:
  - bash <(curl -s https://codecov.io/bash)
sudo: false
